# Generated by Django 5.2.17 on 2026-09-14 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.text import slugify


def populate_project_slugs(apps, schema_editor):
    Project = apps.get_model("portfolio", "Project")
    used = set()
    for project in Project.objects.order_by("pk"):
        base = slugify(project.title_en) or f"project-{project.pk}"
        slug = base
        n = 2
        while slug in used:
            slug = f"{base}-{n}"
            n += 1
        used.add(slug)
        project.slug = slug
        project.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, help_text="Emoji, CSS class, or icon URL", max_length=300)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("language", "Language"),
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("database", "Database"),
                            ("infrastructure", "Infrastructure"),
                            ("devops", "DevOps"),
                            ("data", "Data"),
                            ("tools", "Tools"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="projectlink",
            old_name="label",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="projectlink",
            old_name="href",
            new_name="url",
        ),
        migrations.AddField(
            model_name="projectlink",
            name="icon",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="projectlink",
            name="type",
            field=models.CharField(
                choices=[
                    ("live", "Live Website"),
                    ("github", "GitHub"),
                    ("docs", "Documentation"),
                    ("demo", "Demo"),
                    ("youtube", "YouTube"),
                    ("article", "Article"),
                    ("repository", "Repository"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description_en",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description_fa",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="project",
            name="role_en",
            field=models.TextField(blank=True, help_text="One role per line, e.g. Backend Engineer"),
        ),
        migrations.AddField(
            model_name="project",
            name="role_fa",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product", "Product"),
                    ("platform", "Platform"),
                    ("open_source", "Open Source"),
                    ("infrastructure", "Infrastructure"),
                    ("content", "Content"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("shipped", "Shipped"),
                    ("maintained", "Maintained"),
                    ("archived", "Archived"),
                ],
                default="shipped",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="started_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(blank=True, related_name="projects", to="portfolio.technology"),
        ),
        migrations.RunPython(populate_project_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=240)),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("screenshot", "Screenshot"),
                            ("architecture", "Architecture"),
                            ("dashboard", "Dashboard"),
                            ("mobile", "Mobile"),
                            ("diagram", "Diagram"),
                            ("video", "Video"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("is_cover", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project media",
                "ordering": ["order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_cover", True)),
                        fields=("project",),
                        name="unique_project_cover_media",
                    ),
                ],
            },
        ),
    ]
